### PR TITLE
Issue 299: Check columnsToIndex depending on user input

### LINKED ISSUE #299: Conflicting "columnsToIndex" comparison
## What went wrong?
Appends fail when specifying `columnsToIndex` with `Transformation` type.

#### 1. Code that triggered the bug, or steps to reproduce:
```
data.write.mode("overwrite").format("qbeast").option("columnsToIndex", "id:linear").save(tmpDir)
data.write.mode("append").format("qbeast").option("columnsToIndex", "id:linear").save(tmpDir)
```

#### 6. Stack trace:
```
Columns to index 'id:linear' do not match existing index id.
org.apache.spark.sql.AnalysisException: Columns to index 'id:linear' do not match existing index id.
	at org.apache.spark.sql.AnalysisExceptionFactory$.create(AnalysisExceptionFactory.scala:55)
	at io.qbeast.spark.table.IndexedTableImpl.isNewRevision(IndexedTable.scala:271)
	at io.qbeast.spark.table.IndexedTableImpl.save(IndexedTable.scala:337)
```

### PR DESCRIPTION
**Pull request by Jiaweihu08**
## Description
Fixes #299. It compares the `columnsToIndex` to `Transformer` `columnName` or `spec` depending on user input.

## Type of change

Bug Fix

## Checklist:

Here is the list of things you should do before submitting this pull request:

- [x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [ ] Add comments to the code (make it easier for the community!).
- [ ] Change the documentation.
- [x] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)

Test `columnsToIndex` comparison

### CODE REVIEW

File: core/src/main/scala/io/qbeast/core/model/RevisionClasses.scala [hunk 1]
```diff
@@ -152,7 +152,15 @@ final case class Revision(
    *   true if the revision indexes all and only the provided columns.
    */
   def matchColumns(columnsToIndex: Seq[String]): Boolean = {
-    columnsToIndex.toSet == columnTransformers.map(_.columnName).toSet
+    columnsToIndex.size == columnTransformers.size && columnsToIndex
+      .zip(columnTransformers)
+      .forall { case (columnToIndex, t) =>
+        if (columnToIndex.contains(":")) {
+          columnToIndex == t.spec
```
Comment (osopardo1) [inline core/src/main/scala/io/qbeast/core/model/RevisionClasses.scala:159]: Shouldn't we compare the name in the `columnToIndex` with the name in `t` before?

Comment (Jiaweihu08) [reply core/src/main/scala/io/qbeast/core/model/RevisionClasses.scala:159]: When `columnToIndex` contains `":"` it is a spec in the form of `"col_1:linear"`. In other words, the user here is specifying the transformation it wants to do with `col_1`.

Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/RevisionClasses.scala:159]: oohhh, I see...

I think it's safer to use Regex to enforce the format of columnName:transformationType and compare each other separately.

**Review by osopardo1 — APPROVED** [review]
