### PR TITLE
Issue 312: Optimization should not introduce data changes.

### LINKED ISSUE #312: Optimization should not introduce data change
## What went wrong?
Optimization should not produce data change when reindexing a list of files. In other words, all `FileActions` created by optimization should have `dataChange` set to `false.`

Otherwise, optimizations will fail concurrency checks from Delta Lake as they involve files concurrent readers should have accessed.

## How to reproduce?

1. Set up a low-latency writing process
2. Run optimization on the same table

```
Exception in thread "main" io.delta.exceptions.ConcurrentAppendException: Files were added to the root of the table by a concurrent update. Please try the operation again.
Conflicting commit: {"timestamp":1712912526288,"operation":"WRITE","operationParameters":{"mode":Append},"readVersion":317,"isolationLevel":"Serializable","isBlindAppend":true,"operationMetrics":{"numFiles":"11","numOutputRows":"29974","numOutputBytes":"1598758"},"engineInfo":"Apache-Spark/3.5.0 Delta-Lake/3.1.0","txnId":"d7ccb149-a3d3-449e-b21e-06f3ee27d711"}
```

### 6. Stack Trace:
```
Exception in thread "main" io.delta.exceptions.ConcurrentAppendException: Files were added to the root of the table by a concurrent update. Please try the operation again.
Conflicting commit: {"timestamp":1712912526288,"operation":"WRITE","operationParameters":{"mode":Append},"readVersion":317,"isolationLevel":"Serializable","isBlindAppend":true,"operationMetrics":{"numFiles":"11","numOutputRows":"29974","numOutputBytes":"1598758"},"engineInfo":"Apache-Spark/3.5.0 Delta-Lake/3.1.0","txnId":"d7ccb149-a3d3-449e-b21e-06f3ee27d711"}
Refer to https://docs.delta.io/latest/concurrency-control.html for more details.
	at org.apache.spark.sql.delta.DeltaErrorsBase.concurrentAppendException(DeltaErrors.scala:2300)
	at org.apache.spark.sql.delta.DeltaErrorsBase.concurrentAppendException$(DeltaErrors.scala:2291)
	at org.apache.spark.sql.delta.DeltaErrors$.concurrentAppendException(DeltaErrors.scala:3203)
	at org.apache.spark.sql.delta.ConflictChecker.$anonfun$checkForAddedFilesThatShouldHaveBeenReadByCurrentTxn$1(ConflictChecker.scala:305)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.delta.ConflictChecker.recordTime(ConflictChecker.scala:499)
	at org.apache.spark.sql.delta.ConflictChecker.checkForAddedFilesThatShouldHaveBeenReadByCurrentTxn(ConflictChecker.scala:276)
	at org.apache.spark.sql.delta.ConflictChecker.checkConflicts(ConflictChecker.scala:142)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl.checkForConflictsAgainstVersion(OptimisticTransaction.scala:1882)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl.checkForConflictsAgainstVersion$(OptimisticTransaction.scala:1872)
	at org.apache.spark.sql.delta.OptimisticTransaction.checkForConflictsAgainstVersion(OptimisticTransaction.scala:142)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl.$anonfun$checkForConflicts$10(OptimisticTransaction.scala:1860)
	at org.apache.spark.sql.delta.OptimisticTransactionImpl.$anonfun$checkForConflicts$10$adapted(OptimisticTransaction.scala:1856)
```

### PR DESCRIPTION
**Pull request by Jiaweihu08**
## Description
Fixes #312 

## Type of change

- This is a bug fix

## Checklist:
- [x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add comments to the code (make it easier for the community!).
- [ ] Change the documentation.
- [x] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)

1. Optimizations should use `SnapshotIsolation,` which is to be found in the `CommitInfo`.
2. AddFile and RemoveFile should have `dataChange=false.`

### CODE REVIEW

**Comment by Jiaweihu08** [comment]
To minimize its effect on concurrent operations, the **compaction** command from `delta` sets `dataChange` to `false` for all `AddFile` and `RemoveFile.` This command also has the isolation level `SnapshotIsolation.`

```
import io.delta.tables._

val deltaTable = DeltaTable.forPath(spark, "/path/to/your/delta/table")
deltaTable.optimize().executeCompaction()
```

File: src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala [hunk 1]
```diff
@@ -92,7 +92,7 @@ object RollupDataWriter
     processStats(stats, statsTrackers, fileStatsTracker)
     filesAndStats
       .map(_._1)
-      .map(IndexFiles.toAddFile())
+      .map(IndexFiles.toAddFile(dataChange = true))
```
Comment (fpj) [inline src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala:95]: Do we roll up during optimize calls, if so, should data change really be true?

File: src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala [hunk 2]
```diff
@@ -140,16 +140,20 @@ case class BlockWriter(
               |size=${file.size},
               |modificationTime=${file.modificationTime},
               |revision=${file.revisionId}""".stripMargin.replaceAll("\n", " "))
-      val addFile = IndexFiles.toAddFile()(file)
+      val addFile = IndexFiles.toAddFile(dataChange = true)(file)
```
Comment (fpj) [inline src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: Could this also be executed during an optimization step, in which case data change should be false? I'm a bit unclear on the criteria to determine whether data change should be true or false in this code.

**Review by fpj — CHANGES_REQUESTED** [review]
I have a couple of clarification questions for peace of mind.

**Comment by Jiaweihu08** [comment]
> > To minimize its effect on concurrent operations, the **compaction** command from `delta` sets `dataChange` to `false` for all `AddFile` and `RemoveFile.` This command also has the isolation level `SnapshotIsolation.`
> > ```
> > import io.delta.tables._
> > 
> > val deltaTable = DeltaTable.forPath(spark, "/path/to/your/delta/table")
> > deltaTable.optimize().executeCompaction()
> > ```
> 
> Thanks, @Jiaweihu08 . Could you also point to the delta compaction code (github link to the code) that we talked about offline?

[Here](https://github.com/delta-io/delta/blob/e1063a1bfafd06d57efc4b2f9bd89c7a9051dbec/spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala#L448C26-L448C42) the `OptimizeTableCommand` tags the obtained `AddFile`s with `dataChange=false,` the same happens for the `RemoveFile`s [later on](https://github.com/delta-io/delta/blob/e1063a1bfafd06d57efc4b2f9bd89c7a9051dbec/spark/src/main/scala/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala#L454). 

I tested the command locally, and these changes are observed in the delta log.

File: src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala (hunk 1 above)
Comment (Jiaweihu08) [reply src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala:95]: Rollup happens before any data is written. The line outlined here is executed in regular writing.

File: src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala (hunk 2 above)
Comment (Jiaweihu08) [reply src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: `BlockWriter` for some reason is not currently used anywhere. As files contain more than one block, all writes are handles through `IndexFileWriter.`

Comment (fpj) [reply src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: OK, in this case is the correct course of action to deprecate `BlockWriter`? If you confirm, then let's please create an issue to remove it separately.

Otherwise, I'm unsure about the correct way to set the flag here. If we are to deprecate this class to then remove, then we don't need to worry about maintaining it.

Comment (Jiaweihu08) [reply src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: I opened issue #314 for this.

Comment (fpj) [reply src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: As per @Jiaweihu08 offline, it is making the value of the flag explicit.

Comment (fpj) [reply src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: As per @Jiaweihu08 offline, it is making the value of the flag explicit.

**Review by fpj — APPROVED** [review]
+1, lgtm
