### PR TITLE
Fixed indexing columns with unique values

### LINKED ISSUE #128: Exception on cubeId on DF with single row
## What went wrong?

Indexing a DataFrame on a column of type Int and with a single row throws an exception. It seems related to how we estimate the space with Integers, since I can't reproduce the bug with Strings.

### 1. Code that triggered the bug, or steps to reproduce:

```scala
// This fails
List(95).toDF.write.format("qbeast").option("columnsToIndex","value").save("/tmp/debug-assert")
// While this works
List("95").toDF.write.format("qbeast").option("columnsToIndex","value").save("/tmp/debug-assert2")
```

### 2. Branch and commit id:
Pull request: https://github.com/Qbeast-io/qbeast-spark/pull/124
Branch: `42-table-writes-catalog`
Commit id: 8894e91a94e6e595cd702d9d5194f094713d91ee

### 3. Spark version:
3.1.3

### 4. Hadoop version:
3.2.0

### 5. How are you running Spark?
Local

### 6. Stack trace:

```java
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:268)
        at io.qbeast.core.model.CubeId$.containers(CubeId.scala:66)
        at io.qbeast.core.model.CubeWeightsBuilder.resultInternal(CubeWeights.scala:101)
        at io.qbeast.core.model.CubeWeightsBuilder.result(CubeWeights.scala:92)
        at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$estimatePartitionCubeWeights$4(OTreeDataAnalyzer.scala:161)
        at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)

```

### PR DESCRIPTION
**Pull request by osopardo1**
## Description

Fixes #128. 

## Type of change

When indexing a column with the same value, an IdentityTransformation is instantiated. A Transformation is in charge of mapping the original values of the column to a [0.0, 1.0] space. In the case of IdentityTransformation, the method was returning the `value.byteValue()`, which can give you a `Double` up to 2^8. 

We solved this by changing `IdentityTransformation` to `IdentityToZeroTransformation` and returning 0.0 if the number corresponds to the transformation value.

## Checklist:

Here is the list of things you should do before submitting this pull request:

- [x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add comments to the code (make it easier for the community!).
- [x] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)

- I changed one line of an existing test because this was badly designed. It checked if qbeast could index a column with the same value, but that value was 1. So, when transforming the value, it was in the [0.0, 1.0] range and no requirement failed. I change this value to 10.

### CODE REVIEW

File: core/src/main/scala/io/qbeast/core/transform/Transformation.scala [hunk 1]
```diff
@@ -47,12 +47,11 @@ trait OrdinalTransformation extends Transformation {
...
  */
-case class IdentityTransformation(newVal: Any) extends Transformation {
+case class IdentityToZeroTransformation(identityValue: Any) extends Transformation {
 
   @inline
   override def transform(value: Any): Double = value match {
-    case v: Number =>
-      v.byteValue()
+    case v: Number if v == identityValue => 0.0
   }
```
Comment (Adricu8) [inline core/src/main/scala/io/qbeast/core/transform/Transformation.scala:55]: Is the `if v == identityValue` really needed?

File: core/src/main/scala/io/qbeast/core/transform/LinearTransformation.scala [hunk 2]
```diff
@@ -77,7 +77,7 @@ case class LinearTransformation(
           otherNullValue,
           orderedDataType)
           .asInstanceOf[Transformation]
-      case IdentityTransformation(newVal) =>
+      case IdentityToZeroTransformation(newVal) =>
         val otherNullValue =
           LinearTransformationUtils.generateRandomNumber(
             min(minNumber, newVal),
```
Comment (Adricu8) [inline core/src/main/scala/io/qbeast/core/transform/LinearTransformation.scala:83]: I understand the name change comes from the fact that the IdentityTransformation will always map the values to zero for the index by default, right?

**Review by Adricu8 — COMMENTED** [review]
Good job, the changes seem pretty straightforward :)

File: core/src/main/scala/io/qbeast/core/transform/LinearTransformation.scala (hunk 2 above)
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/transform/LinearTransformation.scala:83]: Yes, it's purely a naming convention :smile:

File: core/src/main/scala/io/qbeast/core/transform/Transformation.scala (hunk 1 above)
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/transform/Transformation.scala:55]: I'm not entirely sure, but if this transformation is trying to transform a value that is not the original one, it should, at least, be noticed (because that can lead to the bad behavior of the index).

**Review by Adricu8 — APPROVED** [review]
