### PR TITLE
Issue 315: Correct cube element counts for rollup during optimization

### LINKED ISSUE #315: Incorrect Rollup cube element counts
## What went wrong?
Stale **blocks** have **offsets** that belong to the subtree due to the constant evolution of the **index**.

When optimizing such an index, the number of elements for each cube is unknown and can only be obtained after the records are indexed.

We now compute the cube element counts using their current value, ignoring the fact that **offsets** no longer belong to the current cube.

#### Hadoop version: `3.3.4`

### PR DESCRIPTION
**Pull request by Jiaweihu08**
## Description

Fixes #315 

Instead of ignoring offsets, cube element counts are computed from the extended data.

## Type of change

It is a bug fix: #315

## Checklist:

- [x] New feature/bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)
Test correct rollup result: `RollupDataWriterTest`

### CODE REVIEW

File: src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala [hunk 1]
```diff
@@ -140,16 +140,20 @@ case class BlockWriter(
               |size=${file.size},
               |modificationTime=${file.modificationTime},
               |revision=${file.revisionId}""".stripMargin.replaceAll("\n", " "))
-      val addFile = IndexFiles.toAddFile()(file)
+      val addFile = IndexFiles.toAddFile(dataChange = true)(file)
```
Comment (osopardo1) [inline src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:143]: Wasn't that commited already in #313 ?

**Review by osopardo1 — COMMENTED** [review]
Just one stupid doubt, otherwise lgtm

File: src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala [hunk 2]
```diff
@@ -314,22 +314,28 @@ object RollupDataWriter
...
-      indexFiles: Seq[IndexFile]): Map[CubeId, CubeId] = {
+  private def computeRollup(revision: Revision, extendedData: DataFrame): Map[CubeId, CubeId] = {
+    import extendedData.sparkSession.implicits._
+
     val desiredFileSize = revision.desiredCubeSize
     val rollup = new Rollup(desiredFileSize)
-    indexFiles
-      .flatMap(_.blocks)
-      .foreach(block => rollup.populate(block.cubeId, block.elementCount.toDouble))
+    extendedData
```
Comment (osopardo1) [inline src/main/scala/io/qbeast/spark/delta/writer/RollupDataWriter.scala:329]: I would add a comment explaining this calculation.

**Review by osopardo1 — APPROVED** [review]
