### PR TITLE
Issue 292: Merge main-1.0.0 into main

### LINKED ISSUE #226: Appends that don't update cube weights
## What went wrong?
The current **weight merge** can push append records to levels beyond estimation, and there are scenarios where new **blocks** are added to cubes without updating their `maxWeights`.

When the existing index is relatively large in comparison to that of the appending data, the estimated cube weights wil reduce significantly because of the merge. This pushes records down to the subtrees, and can reach levels that are not present in the estimation index.

For example, say that `c1` is a leaf cube with a `NormalizedWeight` of 2.0 for the appending data. After merging its weight is reduced to say 0.8. Some records from `c1`'s domain, specifically those with weights between 0.8 and 1.0, will be distributed among its descendants in the following fashin:
- If `c1` in the existing index is also a leaf cube, child cubes will be created for the allocation of these records, creating one extra level at max.
- If the **existing index** has a subtree for `c1`, however, these records will be indexed accordingly but the blocks will be added without updating the index, for the weight merge is already done.

During an experiment with 30 appends, **~45%** of the append blocks experience this issue.

### 2. Branch and commit id:
`main`, [f066acf](https://github.com/Qbeast-io/qbeast-spark/commit/f066acfa640e795459bb9ff815b641377660bd43)

### 3. Spark version:
`3.4.1`

### 4. Hadoop version:
`3.3.4`

### 5. How are you running Spark?
`locally`

### LINKED ISSUE #292: Merge main-1.0.0 into main
There are currently two main branches for historical reasons, `main` and `main-1.0.0`. This is causing a fair amount of confusion about where commits need to go and what branch to use. We need to reconcile the branches and eliminate one. This issue is for merging `main-1.0.0` into `main`, and also eliminate `main-1.0.0` post merge.

### PR DESCRIPTION
**Pull request by osopardo1**
We published release 0.5.0 last January 9th. The last version included changes such as String Indexing and Updates to Spark and Delta 2.4.0. 

Although those changes **significantly improved the distribution of text columns**, we wanted to work on algorithm optimizations that could balance the file layout for all kinds of data.

Closes #292 

# What's changed?

## Roll-Up

One of the key operations for distributing the files evenly is the Roll-Up.

Roll-Up compaction solves the small files problem by **storing the blocks of closely related cubes in a single physical file**. Here “closely related” means that there is a high probability that the cubes contribute data to the same query. 

image

## New Protocol
We've been working on upbreaking changes in the algorithm, **which affects the Metadata written in the Commit Log**.

In summary, instead of having one single file containing one single cube, now we allow **one file to contain multiple cubes stored in `blocks`**. 

image

#### Original protocol metadata:

```json
"tags": {
  "state": "FLOODED",
  "cube": "w",
  "revision": "1",
  "minWeight": "2",
  "maxWeight": "3",
  "elementCount": "4" 
}


```

#### NEW protocol metadata:

```json
"tags": {
  "revision": "1",
  "blocks": [
    {
      "cube": "w",
      "minWeight": 2,
      "maxWeight": 3,
      "replicated": false,
      "elementCount": 4
    },
    {
      "cube": "wg",
      "minWeight": 5,
      "maxWeight": 6,
      "replicated": false,
      "elementCount": 7
    },
  ]
}


```

## Domain-Driven Appends

Another of the upgrades we made in the new code, is using Cube Domains for appending data incrementally. The change uses the existing index during partition-level domain estimation to help reducing the number of cubes with **outdated max weights from 45% to 0.16%**. Or in other words, more balanced files!

Fixes #226. Full details in #227 

## Auto-Indexing

Sometimes the `.option("columnsToIndex", "a,b")` was too hot to handle... That's why we add functionality to **automatically choose the best columns to organize the data**. 

The feature is not enabled by default. If you want to use it, you should add the necessary configuration. 

```shell
spark.qbeast.index.columnsToIndex.auto=true
spark.qbeast.index.columnsToIndex.auto.max=10
```

### CODE REVIEW

**Review by fpj — CHANGES_REQUESTED** [review]
Thanks for the PR, @osopardo1. Is the PR branch missing the changes from PR #254 recently merged?

**Comment by osopardo1** [comment]
There were some inconsistencies with the #247 and #248 changes.

`IndexedTable` was automatically adding the `columnsToIndex` if the `columnSelector` was enabled, while the `QbeastCatalog` implementation was verifying the properties before calling `.save`.

**Comment by osopardo1** [comment]
As @Jiaweihu08 reminded me this morning, we would need to update docs as well!

To do:

- [ ] Remove the Replication feature (or, at least, mark a WARNING)
- [ ] Remove doc of Qbeast-Format 1.0.0. Right now, we are building the code for 0.6.0, not a major version upgrade. 
- [ ] Document RollUp. 
- [ ] Revisit and update versions in `README` and `CONTRIBUTING`.

File: core/src/main/scala/io/qbeast/core/model/CubeId.scala
Comment (Jiaweihu08) [inline core/src/main/scala/io/qbeast/core/model/CubeId.scala:1]: I assume these changes are made by scalastyle?

Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/CubeId.scala:1]: your assumption is correct 🙈

File: README.md [hunk 1]
```diff
@@ -174,6 +174,12 @@ Use [Python index visualizer](./utils/visualizer/README.md) for your indexed tab
 
 Check [here](https://docs.delta.io/latest/releases.html) for **Delta Lake** and **Apache Spark** version compatibility.  
 
+## Format changes
+
+Version 1.0.0 introduced changes in the index metadata format which are
```
Comment (Jiaweihu08) [inline README.md:179]: `0.6.0` instead of `1.0.0`?

Comment (osopardo1) [reply README.md:179]: Yep, need to merge this doc with the `QbeastFormat` instead of maintaining two separate files. 

Maybe we can use this second to state the problem with Replication. WDYT?

File: docs/QbeastFormat1.0.0.md [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+the table data. The utility should implement the following steps:
+
+* remove the information about the replicated cubes from the Delta log metadata
+* for each `add` entry in the Delta log remove all the tags except the 
+  `revision` tag and add the `blocks` tag containing the only block having the
+  same values for the `cube`, `minWeight`, etc attributes. The `replicated`
+  attribute of the block should be `true` if and only if the value of the
+  `state` tag in the original entry is `REPLICATED` or `ANNOUNCED`
+
+To automate the transformation it is strongly recommended to use an
```
Comment (Jiaweihu08) [inline docs/QbeastFormat1.0.0.md:89]: Shouldn't we provide code for this transformation somewhere? No user would like to do such a tedious task.

File: src/main/scala/io/qbeast/spark/delta/CubeInfo.scala [hunk 3]
```diff
@@ -20,9 +20,12 @@ import io.qbeast.core.model.Weight
...
- * @param size      Number of elements of the cube
+ * @param cube
+ *   Id of the cube
+ * @param maxWeight
+ *   Maximum maxWeight of the cube
+ * @param size
+ *   Number of elements of the cube
  */
 
 case class CubeInfo(cube: String, maxWeight: Weight, size: Long)
```
Comment (Jiaweihu08) [inline src/main/scala/io/qbeast/spark/delta/CubeInfo.scala:31]: I don't think this class is used anywhere

File: docs/QbeastFormat1.0.0.md (hunk 2 above)
Comment (osopardo1) [reply docs/QbeastFormat1.0.0.md]: Building a command just for one specific case that is not in production (as far as we know) I don't feel it's necessary. But if your experience tells you is a critical case, we can open an issue and add it after this PR is merged.

File: src/main/scala/io/qbeast/spark/delta/CubeInfo.scala (hunk 3 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/delta/CubeInfo.scala:31]: Totally right. Deleting file 👍

File: src/main/scala/io/qbeast/spark/table/IndexedTable.scala [hunk 4]
```diff
@@ -384,68 +463,34 @@ private[table] class IndexedTableImpl(
...
-      // There's no affected table changes on compaction, so we send an empty object
-      val tableChanges = BroadcastedTableChanges(None, currentIndexStatus, Map.empty)
-      val fileActions =
-        dataWriter.compact(tableID, schema, currentIndexStatus, tableChanges)
-      (tableChanges, fileActions)
-
-    }
-
-  }
+  override def compact(revisionID: RevisionID): Unit = optimize(revisionID)
```
Comment (Jiaweihu08) [inline src/main/scala/io/qbeast/spark/table/IndexedTable.scala:494]: Do we still need this command?

Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/table/IndexedTable.scala:494]: I guess we don't since the only purpose it's calling `optimize`.

File: src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala [hunk 5]
```diff
@@ -180,8 +183,10 @@ case class DeltaQbeastSnapshot(protected override val snapshot: Snapshot)
...
   /**
    * Loads the dataset of qbeast blocks for a given revision
-   * @param revisionID the revision identifier
-   * @return the Dataset of QbeastBlocks
+   * @param revisionID
+   *   the revision identifier
+   * @return
+   *   the Dataset of QbeastBlocks
    */
   def loadRevisionBlocks(revisionID: RevisionID): Dataset[AddFile] = {
```
Comment (Jiaweihu08) [inline src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala:191]: We should rename `loadRevisionBlocks` as well as `loadStagingBlocks` since `Block` and `AddFile` no longer have a one-to-one mapping.

I suggest something along the lines of `longRevisionAddFiles`.

File: src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala [hunk 6]
```diff
@@ -26,7 +40,7 @@ class QueryExecutorTest extends QbeastIntegrationTestSpec with QueryTestSpec {
     val allDeltaFiles = deltaLog.update().allFiles.collect()
     val allFiles = allDeltaFiles.map(_.path)
 
-    val matchFiles = queryExecutor.execute().map(_.path)
+    val matchFiles = queryExecutor.execute().map(_.file.path).toSet
```
Comment (Jiaweihu08) [inline src/test/scala/io/qbeast/spark/index/query/QueryExecutorTest.scala:43]: Redundant `toSet`

File: docs/QbeastFormat.md [hunk 7]
```diff
@@ -18,59 +18,70 @@ Following each write transaction is the creation of a new log file. **Table-leve
...
+| `cube`            | Identifies the current `block`'s `cube` from the `tree`.                                                                                                                                                                                                                                                  |
+| `state`           | Of the `block` determines the **READ** and **WRITE** protocols. It can be `FLOODED`, `ANNOUNCED`, or `REPLICATED`.                                                                                                                                                                                        |
+| `weightMax/weightMin` | Each element gets assigned with a uniformly created `weight` parameter. `weightMin` and `weightMax` define the range of weights that the `block` can contain.                                                                                                                                             |
```
Comment (Jiaweihu08) [inline docs/QbeastFormat.md:45]: `minWeight`, `maxWeight`(?)

File: src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala (hunk 5 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala:191]: Sounds good. Should the name be reduced to "files" instead of using the AddFiles? 

I would rename the `loadStagingBlocks` for `loadStagingFiles` as well.

File: docs/QbeastFormat.md [hunk 8]
```diff
@@ -90,12 +101,16 @@ And here the changes on `Metadata` `configuration` map
...
 
-A more closer look to the `qb.revision.1`:
+| Term                    | Description                                         |
+|-------------------------|-----------------------------------------------------|
+| `qbeast.lastRevisionID` | A pointer to the last revision available.           |
+| `qb.revision.$number`   | The characteristics of the Revision, in JSON style. |
+
+### Revision
+
+A more closer look to the `qb.revision.$number`:
```
Comment (Jiaweihu08) [inline docs/QbeastFormat.md:113]: "A closer look at `qb.revision.$number`"

File: docs/QbeastFormat.md (hunk 7 above)
Comment (osopardo1) [reply docs/QbeastFormat.md:45]: I would delete this table because the info is duplicated, sorry for the inconvenience.

File: docs/QbeastFormat1.0.0.md (hunk 2 above)
Comment (Jiaweihu08) [reply docs/QbeastFormat1.0.0.md]: agree

File: src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala (hunk 5 above)
Comment (Jiaweihu08) [reply src/main/scala/io/qbeast/spark/delta/DeltaQbeastSnapshot.scala:191]: Agree

**Comment by osopardo1** [comment]
This is taking longer than expected...

But to summarize:

- Updated documentation according to the new version.
- Delete `compact()` command, which was just calling `optimize()` underneath.
- Fix tests calling `compact()`. 
- Remove unnecessary classes (`CubeInfo`).
- Solve inconsistencies with the https://github.com/Qbeast-io/qbeast-spark/pull/247 and https://github.com/Qbeast-io/qbeast-spark/pull/248 changes.

**Comment by osopardo1** [comment]
After some discussion, we agreed that:

- Compact() command stays where it is.
- We will open an issue to remove the operation and apply indexation when optimizing the staging area (further details TBD)

These two things would help with easier review and testing. 

Thanks, folks, On my way to update & merge 😄

**Review by Jiaweihu08 — APPROVED** [review]

File: docs/QbeastFormat0.6.0.md [hunk 9]
```diff
@@ -0,0 +1,85 @@
+# QbeastFormat 0.6.0
+
+**The version 0.6.0 introduces a new format for the Qbeast tables.**
```
Comment (fpj) [inline docs/QbeastFormat0.6.0.md:3]: Are there any compatibility implications to tables created with earlier versions that we need to highlight here?

File: docs/QbeastFormat.md
Comment (fpj) [inline docs/QbeastFormat.md:1]: I'm wondering if we need to say anywhere that this is the format up to version `0.5.0`?

File: core/src/main/scala/io/qbeast/core/model/ColumnsToIndexSelector.scala [hunk 10]
```diff
@@ -0,0 +1,36 @@
+package io.qbeast.core.model
```
Comment (fpj) [inline core/src/main/scala/io/qbeast/core/model/ColumnsToIndexSelector.scala:1]: I'm wondering why the license header checker is not capturing that this file is missing a license header altogether.

File: core/src/main/scala/io/qbeast/core/model/Block.scala [hunk 11]
```diff
@@ -0,0 +1,77 @@
+/*
```
Comment (fpj) [inline core/src/main/scala/io/qbeast/core/model/Block.scala:1]: This is not the right license header, I'm wondering how the build is passing with incorrect headers, is it only processing `src/` and not `core/`?

File: src/main/scala/io/qbeast/spark/delta/IndexFiles.scala [hunk 12]
```diff
@@ -0,0 +1,199 @@
...
+    parser.nextToken()
+    while (parser.hasToken(JsonToken.FIELD_NAME)) {
+      parser.nextToken()
+      parser.currentName() match {
+        case "cubeId" => builder.setCubeId(CubeId(dimensionCount, parser.getValueAsString()))
+        case "minWeight" => builder.setMinWeight(Weight(parser.getValueAsInt()))
+        case "maxWeight" => builder.setMaxWeight(Weight(parser.getValueAsInt()))
+        case "elementCount" => builder.setElementCount(parser.getValueAsLong())
+        case "replicated" => builder.setReplicated(parser.getValueAsBoolean())
+        case name => throw new JsonParseException(parser, s"Unexpected field '${name}'")
```
Comment (fpj) [inline src/main/scala/io/qbeast/spark/delta/IndexFiles.scala:189]: Could we please create an issue to add unit test cases that validate that this code throws when expected? Codecov is complaining correctly about lines 189 and 194.

File: src/main/scala/io/qbeast/spark/delta/IndexFiles.scala [hunk 13]
```diff
@@ -0,0 +1,199 @@
...
+    generator.close()
+    writer.close()
+    writer.toString()
+  }
+
+  private def decodeBlocks(json: String, dimensionCount: Int, builder: IndexFileBuilder): Unit = {
+    val parser = jsonFactory.createParser(json)
+    parser.nextToken()
+    if (!parser.hasToken(JsonToken.START_ARRAY)) {
+      throw new JsonParseException(parser, "Array start is expected")
```
Comment (fpj) [inline src/main/scala/io/qbeast/spark/delta/IndexFiles.scala:159]: Same issue in this file about not having tests that validate that the code throws as expected.

File: src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala [hunk 14]
```diff
@@ -59,90 +72,74 @@ case class BlockWriter(
...
-        val cleanRow = Seq.newBuilder[Any]
-        cleanRow.sizeHint(row.numFields)
-        for (i <- 0 until row.numFields) {
-          if (!qbeastColumns.contains(i)) {
-            cleanRow += row.get(i, schemaIndex(i).dataType)
-          }
+    val contexts = mutable.Map.empty[CubeId, BlockContext]
+    rows.foreach { row =>
+      val cubeId = revision.createCubeId(row.getBinary(qbeastColumns.cubeColumnIndex))
+      // TODO make sure this does not compromise the structure of the index
```
Comment (fpj) [inline src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:85]: I'd not recommend to have TODOs in the code without a corresponding issue open, otherwise it is easy to forget that such TODOs are there in the code. If there is an issue open, then add the issue number to the comment, pls.

**Review by fpj — CHANGES_REQUESTED** [review]

File: src/main/scala/io/qbeast/spark/table/IndexedTable.scala [hunk 15]
```diff
@@ -244,6 +297,30 @@ private[table] class IndexedTableImpl(
...
+    } else if (!optionalColumnsToIndex && COLUMN_SELECTOR_ENABLED) {
+      data match {
+        case Some(df) => {
+          // If columnsToIndex is NOT present, the column selector is ENABLED and DATA is AVAILABLE
+          // We can automatically choose the columnsToIndex based on dataFrame
+          val columnsToIndex = columnSelector.selectColumnsToIndex(df)
+          parameters + (COLUMNS_TO_INDEX -> columnsToIndex.mkString(","))
+        }
+        case None =>
+          throw AnalysisExceptionFactory.create(
```
Comment (fpj) [inline src/main/scala/io/qbeast/spark/table/IndexedTable.scala:318]: Same issue about the behavior triggering an exception not being tested, let's either add such a test or at least create an issue to remind us that it needs to be done.

File: src/test/scala/io/qbeast/spark/delta/DefaultFileIndexTest.scala [hunk 16]
```diff
@@ -0,0 +1,128 @@
+package io.qbeast.spark.delta
```
Comment (fpj) [inline src/test/scala/io/qbeast/spark/delta/DefaultFileIndexTest.scala:1]: This one also seems to be missing a license header.

File: src/test/scala/io/qbeast/spark/delta/writer/RollupDataWriterTest.scala [hunk 17]
```diff
@@ -0,0 +1,40 @@
+package io.qbeast.spark.delta.writer
```
Comment (fpj) [inline src/test/scala/io/qbeast/spark/delta/writer/RollupDataWriterTest.scala:1]: Missing license header.

File: src/test/scala/io/qbeast/spark/delta/writer/RollupTest.scala [hunk 18]
```diff
@@ -0,0 +1,39 @@
+/*
```
Comment (fpj) [inline src/test/scala/io/qbeast/spark/delta/writer/RollupTest.scala:1]: Incorrect license header.

File: src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala [hunk 19]
```diff
@@ -0,0 +1,119 @@
+package io.qbeast.spark.index
```
Comment (fpj) [inline src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala:1]: Missing license header.

File: src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala [hunk 20]
```diff
@@ -0,0 +1,119 @@
...
+    ).toDF("s", "i")
+
+    // Initialize SparkColumnsToIndexSelector
+    val autoIndexer = SparkColumnsToIndexSelector
+    val selectedColumns = autoIndexer.selectColumnsToIndex(testDF)
+
+    selectedColumns should contain theSameElementsAs testDF.columns
+  })
+
+  // TODO - Check if this should be the default behavior
```
Comment (fpj) [inline src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala:47]: TODO in the code should have an associated issue open.

File: src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala [hunk 21]
```diff
@@ -0,0 +1,119 @@
...
+    val largeColumnDF =
+      Seq((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13))
+        .toDF()
+
+    val autoIndexer = SparkColumnsToIndexSelector
+    val selectedLargeColumns = autoIndexer.selectColumnsToIndex(largeColumnDF)
+    selectedLargeColumns.length shouldBe 10
+  })
+
+  // TODO - Check if this should be the default behavior
```
Comment (fpj) [inline src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala:102]: Same about TODO.

**Review by fpj — CHANGES_REQUESTED** [review]
Some additional comments.

File: docs/QbeastFormat.md
Comment (osopardo1) [reply docs/QbeastFormat.md:1]: I've updated the `QbeastFormat` document to the new version format (from 0.6.0). I think this doc should contain all the time the newest version of the protocol.

In the `QbeastFormat0.6.0.md` the changes are explained. 

Maybe is confusing, and should be better to rename `QbeastFormat0.6.0` to `QbeastFormat0.5.0`. WDYT?

File: docs/QbeastFormat0.6.0.md (hunk 9 above)
Comment (osopardo1) [reply docs/QbeastFormat0.6.0.md:3]: Yep, they are explained in the same document, alongside a set of steps to transform early datasets.

File: core/src/main/scala/io/qbeast/core/model/ColumnsToIndexSelector.scala (hunk 10 above)
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/ColumnsToIndexSelector.scala:1]: Seems like the `core` package (`sbt project qbeastCore`) does not have LICENSE nor any way of creating them. I would open an issue and resolve it in another PR.

File: core/src/main/scala/io/qbeast/core/model/Block.scala (hunk 11 above)
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/Block.scala:1]: Seems so... would add an issue.

File: src/test/scala/io/qbeast/spark/delta/writer/RollupTest.scala (hunk 18 above)
Comment (osopardo1) [reply src/test/scala/io/qbeast/spark/delta/writer/RollupTest.scala:1]: Fixed on bfea6fc2

File: src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala (hunk 19 above)
Comment (osopardo1) [reply src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala:16]: Fixed on bfea6fc2

File: src/test/scala/io/qbeast/spark/delta/writer/RollupDataWriterTest.scala (hunk 17 above)
Comment (osopardo1) [reply src/test/scala/io/qbeast/spark/delta/writer/RollupDataWriterTest.scala:16]: Fixed on bfea6fc2

File: src/test/scala/io/qbeast/spark/delta/DefaultFileIndexTest.scala (hunk 16 above)
Comment (osopardo1) [reply src/test/scala/io/qbeast/spark/delta/DefaultFileIndexTest.scala:16]: Fixed on bfea6fc2

File: core/src/main/scala/io/qbeast/core/model/Block.scala (hunk 11 above)
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/Block.scala:1]: Added headers on 883bed17

File: core/src/main/scala/io/qbeast/core/model/ColumnsToIndexSelector.scala (hunk 10 above)
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/ColumnsToIndexSelector.scala:16]: Added headers on 883bed17

File: src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala (hunk 21 above)
Comment (osopardo1) [reply src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala:117]: This TODO is more complex than I thought.. I will move it to the right place and open an issue about it: to discuss with @SrTangente which is the default behaviour for ColumnSelector.

File: src/main/scala/io/qbeast/spark/table/IndexedTable.scala (hunk 15 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/table/IndexedTable.scala:318]: This is related to https://github.com/Qbeast-io/qbeast-spark/pull/284#discussion_r1540833194

File: src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala (hunk 21 above)
Comment (osopardo1) [reply src/test/scala/io/qbeast/spark/index/SparkColumnsToIndexSelectorTest.scala]: Issue #295 opened

File: src/main/scala/io/qbeast/spark/table/IndexedTable.scala (hunk 15 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/table/IndexedTable.scala:318]: Issue #295 opened

File: src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala (hunk 14 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/delta/writer/BlockWriter.scala:85]: Aaah - this was a pretty old TODO. This is not needed anymore since the search algorithm was modified to accept jumps between branches if it was the case. I would remove it.

File: src/main/scala/io/qbeast/spark/delta/IndexFiles.scala (hunk 13 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/delta/IndexFiles.scala:159]: I would add some test for IndexFiles. Seems there's none specific for the object.

Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/delta/IndexFiles.scala:159]: Issue #296 opened.

File: src/main/scala/io/qbeast/spark/delta/IndexFiles.scala (hunk 12 above)
Comment (osopardo1) [reply src/main/scala/io/qbeast/spark/delta/IndexFiles.scala:189]: Issue #296 opened

**Review by fpj — APPROVED** [review]
+1, lgtm
