### PR TITLE
Issue #515: Add ColumnStats Schema for JSON parsing

### LINKED ISSUE #515: I can't append on a table  indexed with float columns. It is not possible to define columnsStats for float columns
## What went wrong?
I want to index a table on a few float columns because the float transformer expects a float as input. However, in JSON, floats and doubles are encoded in the same way and mapped to Doubles when parsed, causing a ClassCastException. 

## How to reproduce?
It is impossible to define the column's min-max as float instead of Double, as JSON does not distinguish between the two types. So if I do:

```scala
spark.range(10).map(_.toFloat).toDF("f").write.format("qbeast").option("columnsToIndex","f").option("columnStats","""{"f_max":0.0,"f_min":0.0}""").mode("overwrite").save("/tmp/double")
```
I get this:
```
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Float (java.lang.Double and java.lang.Float are in module java.base of loader 'bootstrap')
  at scala.runtime.BoxesRunTime.unboxToFloat(BoxesRunTime.java:111)
  at scala.math.Numeric$FloatIsFractional$.lteq(Numeric.scala:144)
  at io.qbeast.core.transform.IdentityTransformation.merge(IdentityTransformation.scala:56)
  at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.$anonfun$calculateRevisionChanges$4(OTreeDataAnalyzer.scala:101)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at scala.collection.TraversableLike.map(TraversableLike.scala:286)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
  at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.calculateRevisionChanges(OTreeDataAnalyzer.scala:98)
  at io.qbeast.spark.index.DoublePassOTreeDataAnalyzer$.analyze(OTreeDataAnalyzer.scala:280)
  at io.qbeast.spark.index.SparkOTreeManager$.index(SparkOTreeManager.scala:51)
  at io.qbeast.table.IndexedTableImpl.$anonfun$doWrite$2(IndexedTable.scala:457)
  at io.qbeast.spark.delta.DeltaMetadataWriter.$anonfun$writeWithTransaction$5(DeltaMetadataWriter.scala:182)
  at io.qbeast.spark.delta.DeltaMetadataWriter.$anonfun$writeWithTransaction$5$adapted(DeltaMetadataWriter.scala:175)
  at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:223)
  at io.qbeast.spark.delta.DeltaMetadataWriter.writeWithTransaction(DeltaMetadataWriter.scala:175)
  at io.qbeast.spark.delta.DeltaMetadataManager$.updateWithTransaction(DeltaMetadataManager.scala:42)
  at io.qbeast.table.IndexedTableImpl.doWrite(IndexedTable.scala:456)
  at io.qbeast.table.IndexedTableImpl.write(IndexedTable.scala:429)
  at io.qbeast.table.IndexedTableImpl.save(IndexedTable.scala:388)
  at io.qbeast.sources.QbeastDataSource.createRelation(QbeastDataSource.scala:122)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
```
If I try to force the number to be float (at least for Scala) by adding the f at the end of the file (0.0f), I get another error, as the JSON is malformed.
```
scala> spark.range(10).map(_.toFloat).toDF("f").write.format("qbeast").option("columnsToIndex","f").option("columnStats","""{"f_max":0.0f,"f_min":1.0f}""").mode("overwrite").save("/tmp/doube")
                                                                                
scala> spark.range(10).map(_.toFloat).toDF("f").write.format("qbeast").option("columnsToIndex","f").option("columnStats","""{"f_max":0.0f,"f_min":1.0f}""").mode("append").save("/tmp/doube")
java.lang.IllegalArgumentException: f_min does not exist. Available: _corrupt_record
  at org.apache.spark.sql.types.StructType.$anonfun$fieldIndex$1(StructType.scala:310)
  at scala.collection.immutable.Map$Map1.getOrElse(Map.scala:168)
  at org.apache.spark.sql.types.StructType.fieldIndex(StructType.scala:309)
  at org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema.fieldIndex(rows.scala:48)
  at org.apache.spark.sql.Row.getAs(Row.scala:372)
  at org.apache.spark.sql.Row.getAs$(Row.scala:372)
  at org.apache.spark.sql.catalyst.expressions.GenericRow.getAs(rows.scala:27)
  at io.qbeast.table.IndexedTableImpl.$anonfun$isNewRevision$2(IndexedTable.scala:295)
  at io.qbeast.core.transform.LinearTransformer.makeTransformation(LinearTransformer.scala:60)
  at io.qbeast.table.IndexedTableImpl.$anonfun$isNewRevision$3(IndexedTable.scala:297)
  at scala.collection.immutable.List.map(List.scala:293)
  at io.qbeast.table.IndexedTableImpl.isNewRevision(IndexedTable.scala:297)
  at io.qbeast.table.IndexedTableImpl.save(IndexedTable.scala:346)
  at io.qbeast.sources.QbeastDataSource.createRelation(QbeastDataSource.scala:121)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
  at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
  at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
  at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
  at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
  at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:307)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:243)
  ... 47 elided

```

### 2. Branch and commit id:
main ea4bcd8a6c6815fc96484399bb5358bc27146184
and also cugni:next-in-line-rebased. 

### 3. Spark version:
spark 3.5.3, on the main version (commit ea4bcd8a6c6815fc96484399bb5358bc27146184)

### 5. How are you running Spark?
both distributed and local terminal

### PR DESCRIPTION
**Pull request by osopardo1**
## Description

Fixes #515 . 

In this PR, we are adding a way of building a `columnStats` Schema using the current column `Transformers` and the actual `Schema` of the Data. We want to:
- Ensure the fields are properly parsed from the JSON string. 
- If a JSON string is specified, but the row is returned null, we assume the string is not following the correct syntax.

For that, I've added a `QbeastColumnStats` case class that contains the `columnStatsSchema` and the `columnStatsRow`. Also, a `QbeastColumnStatsBuilder` is needed to retrieve all the information given the parameters mentioned above. 

```scala

case class QbeastColumnStats(columnStatsSchema: StructType, columnStatsRow: Row)


object QbeastColumnStatsBuilder {
  /**
   * Builds the QbeastColumnStats
   *
   * @param statsString
   *   the stats in a JSON string
   * @param columnTransformers
   *   the set of columnTransformers to build the Stats from
   * @param dataSchema
   *   the data schema to build the Stats from
   * @return
   */
  def build(
      statsString: String,
      columnTransformers: Seq[Transformer],
      dataSchema: StructType): QbeastColumnStats
}
```

## Type of change

Bug fix.

## Checklist:

Here is the list of things you should do before submitting this pull request:

- [x] New feature / bug fix has been committed following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add logging to the code following the [Contribution guide](https://github.com/Qbeast-io/qbeast-spark/blob/main/CONTRIBUTING.md).
- [x] Add comments to the code (make it easier for the community!).
- [x] Change the documentation.
- [x] Add tests.
- [x] Your branch is updated to the main branch (dependent changes have been merged).

## How Has This Been Tested? (Optional)

Testing different parsings on `QbeastColumnStatsTestBuilder`.

### CODE REVIEW

File: core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+ *   the column stats row
+ */
+case class QbeastColumnStats(columnStatsSchema: StructType, columnStatsRow: Row)
+
+object QbeastColumnStatsBuilder {
+
+  /**
+   * Builds the column stats schema
+   *
+   * For each column transformer, it creates a StructField with it's stats names
```
Comment (Jiaweihu08) [inline core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala:32]: "it creates a StructField with the stats names"

File: core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+ * Container for Qbeast Column Stats
+ *
+ * @param columnStatsSchema
+ *   the column stats schema
+ * @param columnStatsRow
+ *   the column stats row
+ */
+case class QbeastColumnStats(columnStatsSchema: StructType, columnStatsRow: Row)
+
+object QbeastColumnStatsBuilder {
```
Comment (Jiaweihu08) [inline core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala:27]: The builder design pattern follows the syntax of:
```scala
builder
.setAttr1(someAttr1)
.setAttr2(someAttr2)
.setAttr3(someAttr3)
.result()
```
Which isn't the case here.

I'd recommend using an `apply` method with a companion object for `QbeastColumnStats,` which returns `Option[QbeastColumnStats].` The output should be `None` when the requirements are not met.

File: core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala [hunk 3]
```diff
@@ -283,15 +300,26 @@ trait SparkRevisionChangesUtils extends StagingUtils with Logging {
...
+    // 1. Get the columnStats from the options
+    val columnStatsString = options.columnStats.getOrElse("")
+    // 2. Build the QbeastColumnStats
+    val qbeastColumnStats =
+      QbeastColumnStatsBuilder.build(columnStatsString, transformers, dataSchema)
+    // 3. Compute transformations from the columnStats
+    val columnStatsRow = qbeastColumnStats.columnStatsRow
     transformers.map { t =>
-      if (t.stats.statsNames.forall(availableColumnStats.contains)) {
+      try {
```
Comment (Jiaweihu08) [inline core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala:313]: This logic here can be placed in a method in `QbeastColumnStats.`
In this way, the logic will be more clear:
1. We create an object of QbeastColumnStats
2. Then we use this object to create `Transformations.` If the columns are absent in the stats, we log a warning and return `None.`

File: src/test/scala/io/qbeast/spark/index/SparkRevisionChangesUtilsTest.scala [hunk 4]
```diff
@@ -658,4 +661,60 @@ class SparkRevisionChangesUtilsTest
     revision_2.desiredCubeSize shouldBe 10000
   }
 
+  it should "createNewRevision with column stats for all numeric types" in withSpark(spark => {
```
Comment (Jiaweihu08) [inline src/test/scala/io/qbeast/spark/index/SparkRevisionChangesUtilsTest.scala:664]: There's a list of tests at the beginning of this file. It was made for clarity and to organize the tests, as there are too many cases to cover. 

Please add this test to the list and place it in its proper place, i.e., somewhere in the section of _**// Transformation changes (with columnStats)**_

File: core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala (hunk 3 above)
Comment (Jiaweihu08) [reply core/src/main/scala/io/qbeast/spark/index/SparkRevisionFactory.scala:313]: With that, we can also reduce the number of exceptions thrown here.

**Review by Jiaweihu08 — CHANGES_REQUESTED** [review]

File: core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+      val sparkDataType = dataSchema.find(_.name == transformerColumnName) match {
+        case Some(field) => field.dataType
+        case None =>
+          throw AnalysisExceptionFactory.create(
+            s"Column $transformerColumnName not found in the data schema")
+      }
+
+      transformer match {
+        case LinearTransformer(_, _) =>
+          transformerStatsNames.map(statName =>
```
[the remark this answers is not in the document]
Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/QbeastColumnStats.scala:54]: it makes me doubt, but... I think is correct since it is a single stat name, no?

**Review by Jiaweihu08 — APPROVED** [review]
