### PR TITLE
Issue 297: Reduce overhead for CubeDomainsBuilder instantiation

### LINKED ISSUE #297: Overhead during partition cube domain estimation
## What went wrong?
Sending `IndexStatus` to each partition for the creation of a `CubeDomainsBuilder` instance incurs a large amount of overhead.

`IndexStatus` has a list of `Block`s for each associated `CubeId` in `IndexStatus.cubeStatuses`, and the number of `Block`s grows with the number of appends. Meanwhile, this information is unnecessary during domain computation and should be avoided.

Branch: `main`, `main-1.0.0`

Spark version: `3.5.0`

Hadoop version: `3.3.4`

How are you running Spark? `locally`

### PR DESCRIPTION
**Pull request by Jiaweihu08**
This PR Fixes #297 by

1. As the overhead comes from `CubeStatus`, we pass the required objects directly instead of `IndexStatus`
2. Use `Broadcast` so they persist in each worker so we don't have to pass them for each task

### CODE REVIEW

File: src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala [hunk 1]
```diff
@@ -145,13 +145,21 @@ object DoublePassOTreeDataAnalyzer extends OTreeDataAnalyzer with Serializable {
       val numPartitions: Int = weightedDataFrame.rdd.getNumPartitions
       val bufferCapacity: Long = CUBE_WEIGHTS_BUFFER_CAPACITY
 
+      // Broadcast large objects for CubeDomainsBuilder
+      val broadcastExistingCubeWeights = SparkSession.active.sparkContext.broadcast(
```
Comment (osopardo1) [inline src/main/scala/io/qbeast/spark/index/OTreeDataAnalyzer.scala:149]: I would use the same SparkSession.active for both broadcasts

File: core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala [hunk 2]
```diff
@@ -235,22 +204,18 @@ class CubeDomainsBuilder protected (
...
- * @param existingNormalizedWeights
+ * @param existingCubeWeights
  *   Cube Weight of the existing index
- * @param groupCubeSize
- *   partition-level cube size for indexing
  */
-private class WeightAndCountFactory(
-    existingNormalizedWeights: Map[CubeId, NormalizedWeight],
-    groupCubeSize: Int) {
+private class WeightAndCountFactory(existingCubeWeights: Map[CubeId, Weight]) {
```
Comment (osopardo1) [inline core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala:210]: Why Weight instead of NormalizedWeight? Could this affect calculations?

File: core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala [hunk 3]
```diff
@@ -235,22 +204,18 @@ class CubeDomainsBuilder protected (
...
 
   def create(cubeId: CubeId): WeightAndCount =
-    existingNormalizedWeights.get(cubeId) match {
-      case Some(nw: NormalizedWeight) if nw < 1.0 =>
-        new InnerCubeWeightAndCount(Weight(nw))
-      case Some(nw: NormalizedWeight) =>
-        val existingLeafSize = ((groupCubeSize - 1) / nw).toInt
-        new LeafCubeWeightAndCount(existingLeafSize)
+    existingCubeWeights.get(cubeId) match {
```
Comment (osopardo1) [inline core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala:213]: Adding some comments to the code would be great 🙏

**Review by osopardo1 — COMMENTED** [review]
Some comments!

File: core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala (hunk 2 above)
Comment (Jiaweihu08) [reply core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala:210]: Instead of computing `NormalizedWeight` and then using it to compute the `elementCount` for each existing leaf cube, we assume leaf cubes are empty.

This would place more elements in these leaf cubes during indexing. Still, as we are only interested in cube domains, this should be fine with the calculations.

Comment (osopardo1) [reply core/src/main/scala/io/qbeast/core/model/CubeDomainsBuilder.scala:210]: Let's test that this change does not compromise index layout with bigger workloads before introducing it 🙏

**Comment by osopardo1** [comment]
Seems that the change in the code is not affecting the structure of the index in larger appends. 

When @fpj adds his review, I will wrap up and prepare the merge.

**Review by fpj — APPROVED** [review]
+1, lgtm

**Review by osopardo1 — APPROVED** [review]
